language: python
# python:
#   - "3.11-dev"


install:
  - pip install -r requirements.txt

script:
- black --check .
- flake8 --max-line-length=150 --exclude=venv --ignore=E261,F821,W293,W503 .
- coverage run manage.py test
- env


after_scripts:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ID
  secret_access_key: $AWS_KEY
  region: us-west-2
  app: swe1-assignment
  env: Django-app-env
  bucket_name: elasticbeanstalk-us-west-2-225989339915
  on:
    repo: ander9991/swe1-assignment
    branch: main
  skip_cleanup: 'true'